apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
    tier: mongodb-express
spec:


  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: mongodb-express

  template:
    metadata:
      labels:
        app: mongodb
        tier: mongodb-express
    spec:
      volumes:
      - name: mongodb-vol
        persistentVolumeClaim:
          claimName: mongodb-pvc
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-vol
          mountPath: "/data/db"
        env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mongodb-pass
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: mongodb-pass
